# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Generate Toolchain Tarball

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  generate-toolchain-tarball:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Push tag
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install System Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y rpm2cpio cpio curl

      - name: Generate toolchain tarball
        run: |
          ./setup_toolchain.sh --tarball "autosd-toolchain-x86_64.tar.gz" x86_64
          ./setup_toolchain.sh --tarball "autosd-toolchain-aarch64.tar.gz" aarch64
        working-directory: toolchain/autosd_10_gcc

      - name: Store Toolchain Tarball
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: eclipse-score-autosd-toolchain-tarballs
          path: toolchain/autosd_10_gcc/autosd-toolchain-*.tar.gz
  
  release-toolchain-tarball:
    needs: generate-toolchain-tarball
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set Release Name
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "RELEASE_NAME=continuous" >> "$GITHUB_ENV"
          else
            echo "RELEASE_NAME=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
          fi

      - name: Prepare
        run: |
          mkdir -p _build/
      
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          pattern: eclipse-score-autosd-toolchain-tarballs
          merge-multiple: true
          path: _build/

      - name: Check Build Directory
        run: |
          stat _build/autosd-toolchain-aarch64.tar.gz
          stat _build/autosd-toolchain-x86_64.tar.gz

      - name: Delete existing continuous release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: env.RELEASE_NAME == 'continuous'
        run: |
          gh release delete continuous --yes || true
          git tag -d continuous || true
          git push origin :refs/tags/continuous || true

      - name: Create New Release from Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: env.RELEASE_NAME != 'dev'
        run: |
          gh release create "$GITHUB_REF_NAME" \
          --title "$GITHUB_REF_NAME" \
          --generate-notes
 
      - name: Add Tarballs to GH Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          tag_name: ${{ env.RELEASE_NAME }}
          name: ${{ env.RELEASE_NAME }}
          prerelease: true
          files: |
            _build/autosd-toolchain-aarch64.tar.gz
            _build/autosd-toolchain-x86_64.tar.gz
          fail_on_unmatched_files: true
